In [2]:
import pandas as pd

In [4]:
df=  pd.read_csv(r"candy_data.csv", index_col = 0)

,competitorname,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent,pc1,pc2
0,100 Grand,1,0,1,0,0,1,0,1,0,0.732,0.860,66.971725,1.237558,-0.440595
1,3 Musketeers,1,0,0,0,1,0,0,1,0,0.604,0.511,67.602936,1.080002,-0.179078
2,One dime,0,0,0,0,0,0,0,0,0,0.011,0.116,32.261086,0.032130,-0.117532
3,One quarter,0,0,0,0,0,0,0,0,0,0.011,0.511,46.116505,0.229340,-0.113954
4,Air Heads,0,1,0,0,0,0,0,0,0,0.906,0.511,52.341465,-0.602258,-0.785348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Twizzlers,0,1,0,0,0,0,0,0,0,0.220,0.116,45.466282,-0.413842,-0.429604
81,Warheads,0,1,0,0,0,0,1,0,0,0.093,0.116,39.011898,-0.847697,-0.870085
82,Welch√ïs Fruit Snacks,0,1,0,0,0,0,0,0,1,0.313,0.313,44.375519,-0.856319,0.104041
83,Werther√ïs Original Caramel,0,0,1,0,0,0,1,0,0,0.186,0.267,41.904308,0.106555,-0.711204
84,Whoppers,1,0,0,0,0,1,0,0,1,0.872,0.848,49.524113,0.427393,0.686417